#Theme
remote_theme: pages-themes/architect@v0.2.0

# Name of website
title: marlucjo's Github site

# Your name to show in the footer
author: marlucjo

description: A place to share my notes
show_downloads: false
plugins:
  - jekyll-remote-theme
