remote_theme: pages-themes/architect@v0.2.0
title: marlucjo's Github site
description: A place to share my notes
author: marlucjo
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
plugins:
  - jekyll-remote-theme
