#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
#theme: jekyll-theme-midnight
#theme: jekyll-theme-cayman
remote_theme: pages-themes/architect@v0.2.0
plugins: jekyll-remote-theme
title: marlucjo's Github site
#logo: https://pbs.twimg.com/profile_images/378800000795058910/d611cb4aa977700fa86848cf0e27e004_400x400.jpeg  # /assets/img//logo.png
description: A place to share my notes
google_analytics:
show_downloads: false
